01-building-blocks.yaml

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -3,17 +3,38 @@ name: 01 - Building Blocks
 on: push
 
 jobs:
-    echo-hello:
-        runs-on: ubuntu latest
-        steps: 
-            - name: Say Hello
-              run: echo "Hello, world!"
-    echo-goodbye:
-        runs-on: ubuntu latest
-        steps:
-            - name: Failed step
-              run: |
-                echo "I will fail"
-                exit 1
-            - name: Say Goodbye
-             run: echo "Goodbye!"
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Say Hello
+        run: echo "Hello, world!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+        - name: Failed step
+          run: |
+            echo "I will fail"
+            exit 1
+        - name: Say Goodbye
+          run: echo "Goodbye!"
+
+
+name: 01 - Building Blocks
+
+on: push
+
+jobs:
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Say Hello
+        run: echo "Hello, world!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
+      - name: Say Goodbye
+        run: echo "Goodbye!"
